SELECT  T2.TITLE ,T1.BOARD_ID,T1.REPLY_ID,T1.WRITER_ID,T1.CONTENTS,DATE_FORMAT(T1.CREATED_DATE,'%Y-%m-%d') 
FROM USED_GOODS_REPLY T1,
(SELECT BOARD_ID,TITLE FROM USED_GOODS_BOARD 
 WHERE CREATED_DATE BETWEEN '2022-10-1' and '2022-10-31') T2 
 WHERE T1.BOARD_ID = T2.BOARD_ID
 
 ORDER BY T1.CREATED_DATE , T2.TITLE